/-
This file is part of the split `WakkerDebreuKoopmans` module family.
The public import surface remains `WakkerDebreuKoopmans.lean`, now a thin
re-export barrel.
-/

import WakkerDebreuKoopmans.Closure

/-! ## Public theorem axiom audit (M2 essentiality discharge) -/

#print axioms WakkerRoadmap.CertificateChecklist.additiveCommonScaleCertificate_of_tradeoffTransfer_real_from_essential
#print axioms WakkerRoadmap.CertificateChecklist.additive_rep_unique_of_tradeoffTransfer_real_from_essential

/-! ## Public theorem axiom audit (M2 TradeoffTransferCertificate decomposition) -/

#print axioms WakkerRoadmap.CertificateChecklist.tradeoffTransferCertificate_of_offDiagonal_and_onCoordinate
#print axioms WakkerRoadmap.CertificateChecklist.offDiagonalTradeoffTransferCertificate_of_utilityValueRealizingEquivalence_diagnostic
#print axioms WakkerRoadmap.CertificateChecklist.onCoordinateRatioConsistency_of_triangle_through_third_coordinate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_additiveAffineUniquenessCertificate
#print axioms WakkerRoadmap.CertificateChecklist.onCoordinateRatioConsistency_of_coordinateAffineLift
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_standardSequence_Vj_step
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_standardSequence_Vj_arithmetic
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_standardSequence_step_negative_of_strict
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_strictStandardSequence
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_commonStandardSequenceCalibration
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_pairwiseGridNormalizationWitnesses
#print axioms WakkerRoadmap.CertificateChecklist.standardSequenceGridDensityCertificate_real_of_betweenPointsCertificate
#print axioms WakkerRoadmap.CertificateChecklist.standardSequenceGridBetweenPointsCertificate_of_gridDensityCertificate
#print axioms WakkerRoadmap.CertificateChecklist.standardSequenceGridDensity_real_of_betweenPointsCertificate
#print axioms WakkerRoadmap.CertificateChecklist.additiveRealBool_not_standardSequenceGridDensityCertificate_true
#print axioms WakkerRoadmap.CertificateChecklist.additiveRealBool_not_standardSequenceGridDensityCertificate_false
#print axioms WakkerRoadmap.CertificateChecklist.additiveRealBool_archimedean_tradeoff_solvability_insufficient_for_standardSequenceGridDensity
#print axioms WakkerRoadmap.CertificateChecklist.selectedRefinedDenseGridCertificate_real_of_betweenPointsCertificate
#print axioms WakkerRoadmap.CertificateChecklist.selectedRefinedGridBetweenPointsCertificate_of_denseGridCertificate
#print axioms WakkerRoadmap.CertificateChecklist.additiveRealBool_not_selectedRefinedDenseGridCertificate_true
#print axioms WakkerRoadmap.CertificateChecklist.additiveRealBool_not_selectedRefinedDenseGridCertificate_false
#print axioms WakkerRoadmap.CertificateChecklist.additiveRealBool_archimedean_tradeoff_solvability_insufficient_for_selectedRefinedDenseGrid
#print axioms WakkerRoadmap.CertificateChecklist.continuous_coordinateUtility_of_continuityCertificate_univ
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftContinuityInputs_of_monotone_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_selectedRefinedDenseGrid_and_continuityInputs
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_selectedRefinedGridBetweenPoints_and_continuityInputs
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_selectedRefinedDenseGrid_monotone_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_selectedRefinedGridBetweenPoints_monotone_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_strictStandardSequence_and_certificates
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_strictStandardSequence_monotone_rationalImage_and_gridDensity
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_strictStandardSequence_and_gridBetweenPoints
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_strictStandardSequence_monotone_rationalImage_and_gridBetweenPoints
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalImageCertificate_of_coordinateSurjectivityCertificate
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_twoCoord_indiff_of_value_balance
#print axioms WakkerRoadmap.CertificateChecklist.coordinateIntegerSeedCertificate_of_coordinateIntegerImageCertificate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateIntegerSeedCertificate_of_coordinateRationalImageCertificate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequenceIntegerRefinementCertificate_of_integerSeed_and_extensionData
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequenceIntegerRefinementCertificate_of_integerImage_and_extensionData
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequenceIntegerRefinementCertificate_of_rationalImage_and_extensionData
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequenceIntegerRefinementCertificate_of_surjectivity_and_extensionData
#print axioms WakkerRoadmap.CertificateChecklist.exists_strictStandardSequence_hitting_rational_of_rationalImage_and_extensionData
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityRefinedMeshFamilyCertificate_of_rationalImage_and_extensionData
#print axioms WakkerRoadmap.CertificateChecklist.coordinateBetweenPointsCoverageCertificate_of_refinedMeshFamilyCertificate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateDenseRangeCertificate_of_refinedMeshFamilyCertificate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalImageCertificate_of_rationalRefinementBisectionCertificate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateIntegerSeedCertificate_of_rationalRefinementBisectionCertificate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalRefinementBisectionCertificate_of_rationalImage_and_extensionData
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalRefinementBisectionCertificate_of_strictStandardSequenceFamily_and_oneStepBisectionFeeder
#print axioms WakkerRoadmap.CertificateChecklist.oneStepRationalBisectionFeeder_of_explicitRefinedSequence
#print axioms WakkerRoadmap.CertificateChecklist.strictStandardSequenceFamilyWithGridBracket_of_familyAndBrackets
#print axioms WakkerRoadmap.CertificateChecklist.coordinateConnectedContinuityOneStepBracketCertificate_of_coordinateUtilityUnbounded
#print axioms WakkerRoadmap.CertificateChecklist.coordinateConnectedContinuityOneStepBracketCertificate_of_coordinateRationalImageCertificate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateConnectedContinuityOneStepBracketCertificate_of_rationalRefinementBisectionCertificate
#print axioms WakkerRoadmap.CertificateChecklist.rationalRefinementBisection_and_connectedContinuity_of_rationalImage_and_extensionData
#print axioms WakkerRoadmap.CertificateChecklist.rationalRefinementBisection_and_connectedContinuity_of_surjectivity_and_extensionData
#print axioms WakkerRoadmap.CertificateChecklist.coordinateConnectedContinuityOneStepBracketCertificate_of_continuity_standardSequenceIntegerRefinement
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequenceExtensionData_of_restrictedSolvability_and_connectedContinuity
#print axioms WakkerRoadmap.CertificateChecklist.rationalImage_and_extensionData_of_refinementBisection_connectedContinuity
#print axioms WakkerRoadmap.CertificateChecklist.surjectivity_and_extensionData_of_refinementBisection_connectedContinuity_continuity
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalRefinementBisectionCertificate_of_continuity_standardSequenceIntegerRefinement
#print axioms WakkerRoadmap.CertificateChecklist.rationalRefinementBisection_and_connectedContinuity_of_continuity_standardSequenceIntegerRefinement
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequenceIntegerRefinementCertificate_of_refinementBisection_and_connectedContinuity
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityRefinedMeshFamilyCertificate_of_refinementBisection_and_connectedContinuity
#print axioms WakkerRoadmap.CertificateChecklist.nonSurjectiveIntegerAndMeshBridgeOutputs_of_refinementBisection_and_connectedContinuity
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityContinuityCertificate_univ_of_monotone_rationalRefinementBisection
#print axioms WakkerRoadmap.CertificateChecklist.integerRefinement_and_fullContinuity_of_refinementBisection_connectedContinuity_monotone
#print axioms WakkerRoadmap.CertificateChecklist.integerRefinement_and_fullContinuity_of_refinementBisection_connectedContinuity_structuralMonotonicity
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalRefinementBisectionCertificate_of_wakkerStandardSequenceConstructionInput
#print axioms WakkerRoadmap.CertificateChecklist.coordinateConnectedContinuityOneStepBracketCertificate_of_wakkerStandardSequenceConstructionInput
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityContinuityCertificate_univ_of_wakkerStandardSequenceConstructionInput
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_wakkerStandardSequenceConstructionInput
#print axioms WakkerRoadmap.CertificateChecklist.integerRefinement_and_fullContinuity_of_wakkerStandardSequenceConstructionInput
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionInputCertificate_of_surjectivity_extensionData_structuralMonotonicity
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionInputCertificate_of_rationalImage_extensionData_structuralMonotonicity
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionInputCertificate_of_refinementBisection_connectedContinuity_structuralMonotonicity
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionInputCertificate_of_structural
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_structural
#print axioms WakkerRoadmap.CertificateChecklist.integerRefinement_and_fullContinuity_of_structural
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionStructuralInputCertificate_of_continuity
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionStructuralInputCertificate_of_surjectivity
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityUnboundedCertificate_of_standardSequencePair
#print axioms WakkerRoadmap.CertificateChecklist.coordinateSurjectivityCertificate_of_standardSequencePair_continuity
#print axioms WakkerRoadmap.CertificateChecklist.coordinateConnectedContinuityOneStepBracketCertificate_of_standardSequencePair
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequenceExtensionData_of_standardSequencePair_restrictedSolvability
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionStructuralInputCertificate_of_bareAxiom
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionInputCertificate_of_bareAxiom
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_bareAxiom
#print axioms WakkerRoadmap.CertificateChecklist.integerRefinement_and_fullContinuity_of_bareAxiom
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequencePairCertificate_of_seedConstruction
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionBareAxiomInputCertificate_of_seedConstruction
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_seedConstruction
#print axioms WakkerRoadmap.CertificateChecklist.integerRefinement_and_fullContinuity_of_seedConstruction
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequenceSeedConstructionCertificate_of_jointSeedAndExtensibility
#print axioms WakkerRoadmap.CertificateChecklist.coordinateJointSeedAndExtensibilityCertificate_of_components
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequenceSeedConstructionCertificate_of_components
#print axioms WakkerRoadmap.CertificateChecklist.coordinateBidirectionalOneStepExtensibilityCertificate_of_jointSeedAndExtensibility
#print axioms WakkerRoadmap.CertificateChecklist.coordinateSeedIndifferencePairCertificate_of_jointSeedAndExtensibility
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_jointSeedAndExtensibility
#print axioms WakkerRoadmap.CertificateChecklist.coordinateJointSeedAndExtensibilityCertificate_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.coordinateStandardSequenceSeedConstructionCertificate_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionBareAxiomInputCertificate_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceConstructionInputCertificate_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.integerRefinement_and_fullContinuity_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographLevelInputCertificate_of_components
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographConstructionHalfInputCertificate_of_components
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographTopologyHalfInputCertificate_of_components
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographLevelInputCertificate_of_halves
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographConstructionHalfInputCertificate_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographTopologyHalfInputCertificate_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.coordinateBidirectionalOneStepExtensibilityCertificate_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.coordinateSeedIndifferencePairCertificate_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityContinuityCertificate_univ_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.singleCoordinateMonotonicityAxiom_of_monographLevel
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_halves
#print axioms WakkerRoadmap.CertificateChecklist.integerRefinement_and_fullContinuity_of_halves
#print axioms WakkerRoadmap.CertificateChecklist.coordinateBidirectionalOneStepExtensibilityCertificate_of_perCoordinateAlignment
#print axioms WakkerRoadmap.CertificateChecklist.coordinateSeedIndifferencePairCertificate_of_perCoordinateAlignment
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographConstructionHalfInputCertificate_of_perCoordinateAlignment
#print axioms WakkerRoadmap.CertificateChecklist.coordinatePerCoordinateAlignmentCertificate_of_constructionHalf
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographLevelInputCertificate_of_perCoordinateAlignment_and_topologyHalf
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_perCoordinateAlignment_and_topologyHalf
#print axioms WakkerRoadmap.CertificateChecklist.integerRefinement_and_fullContinuity_of_perCoordinateAlignment_and_topologyHalf
#print axioms WakkerRoadmap.CertificateChecklist.coordinatePerCoordinateAlignmentCertificate_of_pointwise
#print axioms WakkerRoadmap.CertificateChecklist.pointwiseAlignmentCertificate_of_perCoordinateAlignment
#print axioms WakkerRoadmap.CertificateChecklist.coordinatePerCoordinateAlignmentCertificate_iff_pointwise
#print axioms WakkerRoadmap.CertificateChecklist.pointwiseAlignmentCertificate_of_quadruple
#print axioms WakkerRoadmap.CertificateChecklist.exists_quadruple_bidirectionalExtensibility_of_pointwiseAlignment
#print axioms WakkerRoadmap.CertificateChecklist.exists_quadruple_descendingSeed_of_pointwiseAlignment
#print axioms WakkerRoadmap.CertificateChecklist.exists_quadruple_ascendingSeed_of_pointwiseAlignment
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleDescendingSeed_of_strictPair_and_indifference
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleAscendingSeed_of_indifference
#print axioms WakkerRoadmap.CertificateChecklist.exists_strictPreferenceSeedPair_of_essential
#print axioms WakkerRoadmap.CertificateChecklist.pointwiseAlignmentCertificate_of_explicitWitnesses
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleBidirectionalExtensibility_of_directional
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleDescendingExtensibility_of_bidirectional
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleAscendingExtensibility_of_bidirectional
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleBidirectionalExtensibility_iff_directional
#print axioms WakkerRoadmap.CertificateChecklist.pointwiseAlignmentCertificate_of_directionalExplicitWitnesses
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleBidirectionalExtensibility_of_connectednessContinuity
#print axioms WakkerRoadmap.CertificateChecklist.oneStepExtensible_of_continuity_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleDescendingExtensibility_of_continuity_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleAscendingExtensibility_of_continuity_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleBidirectionalExtensibility_of_continuity_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleConnectednessContinuityInputCertificate_of_continuity_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleBidirectionalExtensibility_of_coordinateUtilityContinuity_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleBidirectionalExtensibility_of_coordinateUtilityContinuity_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityUnboundedCertificate_of_coordinateSurjectivityCertificate
#print axioms WakkerRoadmap.CertificateChecklist.exists_quadrupleDescendingSeedIndifferenceExplicit_of_bracketing
#print axioms WakkerRoadmap.CertificateChecklist.exists_quadrupleAscendingSeedIndifferenceExplicit_of_bracketing
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleDescendingSeed_of_explicitPair
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleAscendingSeed_of_explicitPair
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleStrictReferenceUtilityOrdering_of_strictPreference
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_iUtilityOrdering_of_seedIndifference_and_strictReference
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_strictDescendingPreference_of_iUtilityOrdering
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleDescendingSeed_of_explicit_alignment
#print axioms WakkerRoadmap.CertificateChecklist.exists_quadrupleDescendingSeed_of_bracketing_alignment
#print axioms WakkerRoadmap.CertificateChecklist.pointwiseAlignmentCertificate_of_bracketing_alignment
#print axioms WakkerRoadmap.CertificateChecklist.pointwiseAlignmentCertificate_of_coordinateWakkerAlignmentData
#print axioms WakkerRoadmap.CertificateChecklist.coordinatePerCoordinateAlignmentCertificate_of_wakkerTopologicalAxiomBundle
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographTopologyHalfInputCertificate_of_wakkerTopologicalAxiomBundle
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographLevelInputCertificate_of_wakkerTopologicalAxiomBundle
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_wakkerTopologicalAxiomBundle
#print axioms WakkerRoadmap.CertificateChecklist.integerRefinement_and_fullContinuity_of_wakkerTopologicalAxiomBundle
#print axioms WakkerRoadmap.CertificateChecklist.wakkerTopologicalAxiomBundle_of_components
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleDescendingSeedBracketingCertificate_of_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleAscendingSeedBracketingCertificate_of_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.coordinateWakkerAlignmentData_of_connected_continuous_unbounded_strictReference
#print axioms WakkerRoadmap.CertificateChecklist.wakkerTopologicalAxiomBundle_of_strictReferenceWitnesses
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_strictReferenceWitnesses
#print axioms WakkerRoadmap.CertificateChecklist.wakkerConstructionCertificate_of_additiveRep
#print axioms WakkerRoadmap.CertificateChecklist.wakkerConstructionCertificate_of_additiveRepHypothesisBundle
#print axioms WakkerRoadmap.CertificateChecklist.additiveRepHypothesisBundle_of_wakkerConstructionCertificate
#print axioms WakkerRoadmap.CertificateChecklist.additiveRepHypothesisBundle_iff_wakkerConstructionCertificate
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_nonempty_of_additiveRepHypothesisBundle
#print axioms WakkerRoadmap.CertificateChecklist.wakker_IV_2_7_of_additiveRepHypothesisBundle
#print axioms WakkerRoadmap.CertificateChecklist.indiffSet_closed_of_preferenceContinuous
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_sum_continuous
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_pullback_preferenceContinuous
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_indiffSet_closed
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_real_pullback_preferenceContinuous
#print axioms WakkerRoadmap.CertificateChecklist.connectedCoordinates_realProduct
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityImage_isPreconnected_of_connected_and_continuous
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityImage_ordConnected_of_real_continuous
#print axioms WakkerRoadmap.CertificateChecklist.coordinateSurjectivityCertificate_of_connected_continuous_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityUnbounded_of_connected_continuous_surjective
#print axioms WakkerRoadmap.CertificateChecklist.oneStepExtensible_of_connected_continuous_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.quadrupleBidirectionalExtensibility_of_connected_continuous_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.singleCoordinateMonotonicityAxiom_of_coordinateMonotonicityCertificate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateMonotonicityCertificate_iff_singleCoordinateMonotonicityAxiom
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityContinuityCertificate_univ_of_connected_monotone_continuous_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityContinuityCertificate_univ_of_connected_structuralMonotonicity_continuous_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographTopologyHalfInputCertificate_of_connected_structuralMonotonicity_continuous_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographTopologyHalfInputCertificate_of_real_preferenceContinuous_structuralMonotonicity_continuous_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographTopologyHalfInputCertificate_of_structuralMonotonicity_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographTopologyHalfInputCertificate_of_monotone_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographTopologyHalfInputCertificate_of_structuralMonotonicity_denseRange
#print axioms WakkerRoadmap.CertificateChecklist.wakkerMonographTopologyHalfInputCertificate_of_structuralMonotonicity_continuity
#print axioms WakkerRoadmap.CertificateChecklist.wakkerRawOutputs_of_perCoordinateAlignment_and_structuralMonotonicity_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.coordinateIntegerImageCertificate_of_twoSidedIntegerRefinementCertificate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateTwoSidedIntegerRefinementCertificate_of_standardSequenceIntegerRefinement
#print axioms WakkerRoadmap.CertificateChecklist.coordinateIntegerImageCertificate_of_standardSequenceIntegerRefinement
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilitySolvabilityCertificate_of_coordinateSurjectivityCertificate
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilitySolvabilityCertificate_of_continuity_univ
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalImageCertificate_of_coordUtilitySolvability_integerImage
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalImageCertificate_of_coordUtilitySolvability_twoSided_nat
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalImageCertificate_of_coordUtilitySolvability_twoSidedIntegerRefinement
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalImageCertificate_of_continuity_twoSidedIntegerRefinement
#print axioms WakkerRoadmap.CertificateChecklist.coordinateRationalImageCertificate_of_continuity_standardSequenceIntegerRefinement
#print axioms WakkerRoadmap.CertificateChecklist.coordinateSurjectivityCertificate_of_continuity_unbounded
#print axioms WakkerRoadmap.CertificateChecklist.coordinateSurjectivityCertificate_of_monotone_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.coordinateMonotonicityCertificate_of_singleCoordinateMonotonicityAxiom
#print axioms WakkerRoadmap.CertificateChecklist.coordinateSurjectivityCertificate_of_singleCoordinateMonotonicityAxiom_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.primitiveAffineLiftCertificates_of_structuralMonotonicity_surjectivity_gridDensity
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_strictStandardSequence_structuralMonotonicity_surjectivity_gridDensity
#print axioms WakkerRoadmap.CertificateChecklist.utilityValueRealizingEquivalence_corrected_of_singleCoordinateMonotonicityAxiom_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_strictStandardSequence_structuralMonotonicity_rationalImage_gridDensity
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_selectedRefinedDenseGrid_structuralMonotonicity_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.coordinateAffineLiftCertificate_of_selectedRefinedGridBetweenPoints_structuralMonotonicity_rationalImage
#print axioms WakkerRoadmap.CertificateChecklist.tradeoffTransferCertificate_of_utilityValueRealizingEquivalence_and_triangle_diagnostic

/-! ## Public theorem axiom audit (M2 diagnostic refutation) -/

#print axioms WakkerRoadmap.CertificateChecklist.additiveBoolReal_not_utilityValueRealizingEquivalence_diagnostic
#print axioms WakkerRoadmap.CertificateChecklist.utilityValueRealizingEquivalence_diagnostic_unattainable_from_additivity

/-! ## Public theorem axiom audit (M2 corrected discharge) -/

#print axioms WakkerRoadmap.CertificateChecklist.offDiagonalTradeoffTransferCertificate_of_utilityValueRealizingEquivalence_corrected
#print axioms WakkerRoadmap.CertificateChecklist.tradeoffTransferCertificate_of_utilityValueRealizingEquivalence_corrected_and_onCoordinate
#print axioms WakkerRoadmap.CertificateChecklist.tradeoffTransferCertificate_of_utilityValueRealizingEquivalence_corrected_and_coordinateAffineLift

/-! ## Public theorem axiom audit (M2 corrected predicate further factoring) -/

#print axioms WakkerRoadmap.CertificateChecklist.utilityValueRealizingEquivalence_corrected_of_jDifferenceRealization_and_bracketing

/-! ## Public theorem axiom audit (M2 TradeoffBracketingForallCertificate discharge) -/

#print axioms WakkerRoadmap.CertificateChecklist.tradeoffBracketingCertificate_of_coordinateUtilityUnbounded
#print axioms WakkerRoadmap.CertificateChecklist.tradeoffBracketingForallCertificate_of_coordinateUtilityUnbounded
#print axioms WakkerRoadmap.CertificateChecklist.additiveBoolReal_coordinateUtilityUnbounded
#print axioms WakkerRoadmap.CertificateChecklist.additiveBoolReal_tradeoffBracketingForallCertificate

/-! ## Public theorem axiom audit (M2 surjectivity route) -/

#print axioms WakkerRoadmap.CertificateChecklist.jDifferenceRealizationCertificate_of_coordinateSurjectivityCertificate
#print axioms WakkerRoadmap.CertificateChecklist.tradeoffBracketingForallCertificate_of_coordinateSurjectivityCertificate
#print axioms WakkerRoadmap.CertificateChecklist.utilityValueRealizingEquivalence_corrected_of_coordinateSurjectivityCertificate

/-! ## Public theorem axiom audit (Archimedean cofinality of V_j) -/

#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_Vj_cofinalBelow_of_strictStandardSequence
#print axioms WakkerRoadmap.CertificateChecklist.additiveRep_Vj_cofinalAbove_of_standardSequence_posStep
#print axioms WakkerRoadmap.CertificateChecklist.coordinateUtilityUnboundedCertificate_of_strictStandardSequence_pair

/-! ## Public theorem axiom audit
(O1 standard-sequence-machinery forward-direction scaffolding) -/

#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage1PivotData_of_essential
#print axioms WakkerRoadmap.CertificateChecklist.additiveRepHypothesisBundle_iff_wakkerStage5AdditiveAssemblyData
#print axioms WakkerRoadmap.CertificateChecklist.WakkerStandardSequenceForwardConstructionBundle.stage2
#print axioms WakkerRoadmap.CertificateChecklist.WakkerStandardSequenceForwardConstructionBundle.stage3
#print axioms WakkerRoadmap.CertificateChecklist.WakkerStandardSequenceForwardConstructionBundle.stage4
#print axioms WakkerRoadmap.CertificateChecklist.WakkerStandardSequenceForwardConstructionBundle.stage5
#print axioms WakkerRoadmap.CertificateChecklist.additiveRepHypothesisBundle_of_wakkerStandardSequenceForwardConstructionBundle
#print axioms WakkerRoadmap.CertificateChecklist.wakker_IV_2_7_of_wakkerStandardSequenceForwardConstructionBundle
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage2NatGridData_of_injectiveStandardSequence
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage3FiniteCutCoverageData_of_surjectiveStandardSequences
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage3FiniteCutCoverageData_of_gridReachability_surjectiveSecondCoord
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage3FiniteCutCoverageData_of_gridReachability_surjectiveFirstCoord
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage4PivotSliceRepresentationData_of_sharedPivot
#print axioms WakkerRoadmap.CertificateChecklist.pairwiseSliceRepresentationsAtPivot_of_stage3FiniteCutCoverage_and_normalization
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage4PivotSliceRepresentationData_of_stage3FiniteCutCoverage_and_normalization
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage4FullPivotUtilityData_of_pairwiseSliceRepresentationsAtPivot
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage4FullPivotUtilityData_of_stage4PivotSliceRepresentationData
#print axioms WakkerRoadmap.CertificateChecklist.allPairsAdditivityCertificate_of_pairwiseSliceRepresentationsAtPivot
#print axioms WakkerRoadmap.CertificateChecklist.allPairsAdditivityCertificate_of_stage4PivotSliceRepresentationData
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStep5StrictMonotonicityCertificate_of_allPairsAdditivity
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStep5StrictMonotonicityCertificate_of_stage4PivotSliceRepresentationData
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStep5CoordinateImageCoverageCertificate_of_residueAtPivot
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStep5CoordinateImageCoverageCertificate_of_stage4PivotSliceRepresentationData
#print axioms WakkerRoadmap.CertificateChecklist.quasiToConcaveStrengtheningCertificate_of_continuity_and_midpoint
#print axioms WakkerRoadmap.CertificateChecklist.twoCoordinateConcavityCertificate_of_continuity_midpoint_and_convexUpperContour
#print axioms WakkerRoadmap.CertificateChecklist.perCoordinateConcavityCertificate_of_perCoordinatePairConcavityAtPivot
#print axioms WakkerRoadmap.CertificateChecklist.perCoordinateConcavityCertificate_of_pairConcavity_and_coordinateImageCoverage_and_continuity
#print axioms WakkerRoadmap.CertificateChecklist.debreu_koopmans_hard_of_pairConcavity_and_coordinateImageCoverage_and_continuity
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage4PivotSliceRepresentationData_of_stage5GlobalGluingData
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage5AdditiveAssemblyData_of_stage5GlobalGluingData
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStandardSequenceForwardConstructionBundle_of_stage5GlobalGluingData
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage5GlobalGluingData_of_additiveRep
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage5GlobalGluingData_of_wakkerStage5AdditiveAssemblyData
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage5GlobalGluingData_iff_wakkerStage5AdditiveAssemblyData
#print axioms WakkerRoadmap.CertificateChecklist.wakkerStage5GlobalGluingData_iff_additiveRepHypothesisBundle
